name: sism
channels:
  - conda-forge
  - defaults
  - pytorch
  - pyg
  - nvidia
dependencies:
  - python=3.11
  - pip
  - notebook
  - matplotlib
  - pytorch::pytorch=2.2.2
  - pytorch-cuda=11.8
  - torchvision==0.17.2
  - conda-forge::rdkit=2023.03.3
  - conda-forge::lightning=2.2.1
  - conda-forge::jupyter
  - pip:
      - nglview
      - tensorboard
      - seaborn
      - ase
      - py3Dmol